# Automatically publish a package to GitHub Packages and the NPM Registry when a release is created

name: Publish Package

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm i
      - run: tsc
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM}}
