name: Tests

on:
  push:
    paths-ignore:
      - 'README.md'
      - '.github/**'
    branches: [ main ]
  pull_request:
    paths-ignore:
      - 'README.md'
      - '.github/**'
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: npm install, build and test
        env:
          API_KEY: ${{ secrets.API_KEY }}
          TEST_SERVER_ID: ${{ secrets.TEST_SERVER_ID }}
        run: | 
          npm install
          npm build
          npm test
